#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDatos.DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FoodTruck")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTM_Clientes(TM_Clientes instance);
    partial void UpdateTM_Clientes(TM_Clientes instance);
    partial void DeleteTM_Clientes(TM_Clientes instance);
    partial void InsertTM_Contabilidad(TM_Contabilidad instance);
    partial void UpdateTM_Contabilidad(TM_Contabilidad instance);
    partial void DeleteTM_Contabilidad(TM_Contabilidad instance);
    partial void InsertTM_Empleados(TM_Empleados instance);
    partial void UpdateTM_Empleados(TM_Empleados instance);
    partial void DeleteTM_Empleados(TM_Empleados instance);
    partial void InsertTM_HamMaker(TM_HamMaker instance);
    partial void UpdateTM_HamMaker(TM_HamMaker instance);
    partial void DeleteTM_HamMaker(TM_HamMaker instance);
    partial void InsertTM_Ingredientes(TM_Ingredientes instance);
    partial void UpdateTM_Ingredientes(TM_Ingredientes instance);
    partial void DeleteTM_Ingredientes(TM_Ingredientes instance);
    partial void InsertTM_Local(TM_Local instance);
    partial void UpdateTM_Local(TM_Local instance);
    partial void DeleteTM_Local(TM_Local instance);
    partial void InsertTM_Menu(TM_Menu instance);
    partial void UpdateTM_Menu(TM_Menu instance);
    partial void DeleteTM_Menu(TM_Menu instance);
    partial void InsertTM_Pedidos(TM_Pedidos instance);
    partial void UpdateTM_Pedidos(TM_Pedidos instance);
    partial void DeleteTM_Pedidos(TM_Pedidos instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::capaDatos.Properties.Settings.Default.FoodTruckConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TM_Clientes> TM_Clientes
		{
			get
			{
				return this.GetTable<TM_Clientes>();
			}
		}
		
		public System.Data.Linq.Table<TM_Contabilidad> TM_Contabilidad
		{
			get
			{
				return this.GetTable<TM_Contabilidad>();
			}
		}
		
		public System.Data.Linq.Table<TM_Empleados> TM_Empleados
		{
			get
			{
				return this.GetTable<TM_Empleados>();
			}
		}
		
		public System.Data.Linq.Table<TM_HamMaker> TM_HamMaker
		{
			get
			{
				return this.GetTable<TM_HamMaker>();
			}
		}
		
		public System.Data.Linq.Table<TM_Ingredientes> TM_Ingredientes
		{
			get
			{
				return this.GetTable<TM_Ingredientes>();
			}
		}
		
		public System.Data.Linq.Table<TM_Local> TM_Local
		{
			get
			{
				return this.GetTable<TM_Local>();
			}
		}
		
		public System.Data.Linq.Table<TM_Menu> TM_Menu
		{
			get
			{
				return this.GetTable<TM_Menu>();
			}
		}
		
		public System.Data.Linq.Table<TM_Pedidos> TM_Pedidos
		{
			get
			{
				return this.GetTable<TM_Pedidos>();
			}
		}

        public object Categories { get; set; }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Clientes")]
	public partial class TM_Clientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cliente_id;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _direccion;
		
		private string _telefono;
		
		private string _correo_electronico;
		
		private System.Nullable<int> _local_id;
		
		private System.Nullable<int> _PedidosID;
		
		private EntitySet<TM_HamMaker> _TM_HamMaker;
		
		private EntityRef<TM_Local> _TM_Local;
		
		private EntityRef<TM_Pedidos> _TM_Pedidos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncliente_idChanging(int value);
    partial void Oncliente_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void Oncorreo_electronicoChanging(string value);
    partial void Oncorreo_electronicoChanged();
    partial void Onlocal_idChanging(System.Nullable<int> value);
    partial void Onlocal_idChanged();
    partial void OnPedidosIDChanging(System.Nullable<int> value);
    partial void OnPedidosIDChanged();
    #endregion
		
		public TM_Clientes()
		{
			this._TM_HamMaker = new EntitySet<TM_HamMaker>(new Action<TM_HamMaker>(this.attach_TM_HamMaker), new Action<TM_HamMaker>(this.detach_TM_HamMaker));
			this._TM_Local = default(EntityRef<TM_Local>);
			this._TM_Pedidos = default(EntityRef<TM_Pedidos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliente_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cliente_id
		{
			get
			{
				return this._cliente_id;
			}
			set
			{
				if ((this._cliente_id != value))
				{
					this.Oncliente_idChanging(value);
					this.SendPropertyChanging();
					this._cliente_id = value;
					this.SendPropertyChanged("cliente_id");
					this.Oncliente_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(20)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_electronico", DbType="NVarChar(100)")]
		public string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				if ((this._correo_electronico != value))
				{
					this.Oncorreo_electronicoChanging(value);
					this.SendPropertyChanging();
					this._correo_electronico = value;
					this.SendPropertyChanged("correo_electronico");
					this.Oncorreo_electronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_local_id", DbType="Int")]
		public System.Nullable<int> local_id
		{
			get
			{
				return this._local_id;
			}
			set
			{
				if ((this._local_id != value))
				{
					if (this._TM_Local.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlocal_idChanging(value);
					this.SendPropertyChanging();
					this._local_id = value;
					this.SendPropertyChanged("local_id");
					this.Onlocal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PedidosID", DbType="Int")]
		public System.Nullable<int> PedidosID
		{
			get
			{
				return this._PedidosID;
			}
			set
			{
				if ((this._PedidosID != value))
				{
					if (this._TM_Pedidos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPedidosIDChanging(value);
					this.SendPropertyChanging();
					this._PedidosID = value;
					this.SendPropertyChanged("PedidosID");
					this.OnPedidosIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TM_HamMaker", Storage="_TM_HamMaker", ThisKey="cliente_id", OtherKey="cliente_id")]
		public EntitySet<TM_HamMaker> TM_HamMaker
		{
			get
			{
				return this._TM_HamMaker;
			}
			set
			{
				this._TM_HamMaker.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Local_TM_Clientes", Storage="_TM_Local", ThisKey="local_id", OtherKey="local_id", IsForeignKey=true)]
		public TM_Local TM_Local
		{
			get
			{
				return this._TM_Local.Entity;
			}
			set
			{
				TM_Local previousValue = this._TM_Local.Entity;
				if (((previousValue != value) 
							|| (this._TM_Local.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Local.Entity = null;
						previousValue.TM_Clientes.Remove(this);
					}
					this._TM_Local.Entity = value;
					if ((value != null))
					{
						value.TM_Clientes.Add(this);
						this._local_id = value.local_id;
					}
					else
					{
						this._local_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Local");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Pedidos_TM_Clientes", Storage="_TM_Pedidos", ThisKey="PedidosID", OtherKey="PedidosId", IsForeignKey=true)]
		public TM_Pedidos TM_Pedidos
		{
			get
			{
				return this._TM_Pedidos.Entity;
			}
			set
			{
				TM_Pedidos previousValue = this._TM_Pedidos.Entity;
				if (((previousValue != value) 
							|| (this._TM_Pedidos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Pedidos.Entity = null;
						previousValue.TM_Clientes.Remove(this);
					}
					this._TM_Pedidos.Entity = value;
					if ((value != null))
					{
						value.TM_Clientes.Add(this);
						this._PedidosID = value.PedidosId;
					}
					else
					{
						this._PedidosID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Pedidos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TM_HamMaker(TM_HamMaker entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = this;
		}
		
		private void detach_TM_HamMaker(TM_HamMaker entity)
		{
			this.SendPropertyChanging();
			entity.TM_Clientes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Contabilidad")]
	public partial class TM_Contabilidad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _registro_id;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _descripcion;
		
		private System.Nullable<decimal> _ingresos;
		
		private System.Nullable<decimal> _gastos;
		
		private System.Nullable<int> _local_id;
		
		private EntitySet<TM_Pedidos> _TM_Pedidos;
		
		private EntityRef<TM_Local> _TM_Local;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onregistro_idChanging(int value);
    partial void Onregistro_idChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OningresosChanging(System.Nullable<decimal> value);
    partial void OningresosChanged();
    partial void OngastosChanging(System.Nullable<decimal> value);
    partial void OngastosChanged();
    partial void Onlocal_idChanging(System.Nullable<int> value);
    partial void Onlocal_idChanged();
    #endregion
		
		public TM_Contabilidad()
		{
			this._TM_Pedidos = new EntitySet<TM_Pedidos>(new Action<TM_Pedidos>(this.attach_TM_Pedidos), new Action<TM_Pedidos>(this.detach_TM_Pedidos));
			this._TM_Local = default(EntityRef<TM_Local>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registro_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int registro_id
		{
			get
			{
				return this._registro_id;
			}
			set
			{
				if ((this._registro_id != value))
				{
					this.Onregistro_idChanging(value);
					this.SendPropertyChanging();
					this._registro_id = value;
					this.SendPropertyChanged("registro_id");
					this.Onregistro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingresos", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ingresos
		{
			get
			{
				return this._ingresos;
			}
			set
			{
				if ((this._ingresos != value))
				{
					this.OningresosChanging(value);
					this.SendPropertyChanging();
					this._ingresos = value;
					this.SendPropertyChanged("ingresos");
					this.OningresosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gastos", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> gastos
		{
			get
			{
				return this._gastos;
			}
			set
			{
				if ((this._gastos != value))
				{
					this.OngastosChanging(value);
					this.SendPropertyChanging();
					this._gastos = value;
					this.SendPropertyChanged("gastos");
					this.OngastosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_local_id", DbType="Int")]
		public System.Nullable<int> local_id
		{
			get
			{
				return this._local_id;
			}
			set
			{
				if ((this._local_id != value))
				{
					if (this._TM_Local.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlocal_idChanging(value);
					this.SendPropertyChanging();
					this._local_id = value;
					this.SendPropertyChanged("local_id");
					this.Onlocal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Contabilidad_TM_Pedidos", Storage="_TM_Pedidos", ThisKey="registro_id", OtherKey="registro_id")]
		public EntitySet<TM_Pedidos> TM_Pedidos
		{
			get
			{
				return this._TM_Pedidos;
			}
			set
			{
				this._TM_Pedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Local_TM_Contabilidad", Storage="_TM_Local", ThisKey="local_id", OtherKey="local_id", IsForeignKey=true)]
		public TM_Local TM_Local
		{
			get
			{
				return this._TM_Local.Entity;
			}
			set
			{
				TM_Local previousValue = this._TM_Local.Entity;
				if (((previousValue != value) 
							|| (this._TM_Local.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Local.Entity = null;
						previousValue.TM_Contabilidad.Remove(this);
					}
					this._TM_Local.Entity = value;
					if ((value != null))
					{
						value.TM_Contabilidad.Add(this);
						this._local_id = value.local_id;
					}
					else
					{
						this._local_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Local");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TM_Pedidos(TM_Pedidos entity)
		{
			this.SendPropertyChanging();
			entity.TM_Contabilidad = this;
		}
		
		private void detach_TM_Pedidos(TM_Pedidos entity)
		{
			this.SendPropertyChanging();
			entity.TM_Contabilidad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Empleados")]
	public partial class TM_Empleados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _empleado_id;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _direccion;
		
		private string _telefono;
		
		private System.Nullable<decimal> _salario;
		
		private System.Nullable<System.DateTime> _fecha_contratacion;
		
		private System.Nullable<int> _local_id;
		
		private EntityRef<TM_Local> _TM_Local;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onempleado_idChanging(int value);
    partial void Onempleado_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnsalarioChanging(System.Nullable<decimal> value);
    partial void OnsalarioChanged();
    partial void Onfecha_contratacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_contratacionChanged();
    partial void Onlocal_idChanging(System.Nullable<int> value);
    partial void Onlocal_idChanged();
    #endregion
		
		public TM_Empleados()
		{
			this._TM_Local = default(EntityRef<TM_Local>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empleado_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int empleado_id
		{
			get
			{
				return this._empleado_id;
			}
			set
			{
				if ((this._empleado_id != value))
				{
					this.Onempleado_idChanging(value);
					this.SendPropertyChanging();
					this._empleado_id = value;
					this.SendPropertyChanged("empleado_id");
					this.Onempleado_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(20)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salario", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> salario
		{
			get
			{
				return this._salario;
			}
			set
			{
				if ((this._salario != value))
				{
					this.OnsalarioChanging(value);
					this.SendPropertyChanging();
					this._salario = value;
					this.SendPropertyChanged("salario");
					this.OnsalarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_contratacion", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_contratacion
		{
			get
			{
				return this._fecha_contratacion;
			}
			set
			{
				if ((this._fecha_contratacion != value))
				{
					this.Onfecha_contratacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_contratacion = value;
					this.SendPropertyChanged("fecha_contratacion");
					this.Onfecha_contratacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_local_id", DbType="Int")]
		public System.Nullable<int> local_id
		{
			get
			{
				return this._local_id;
			}
			set
			{
				if ((this._local_id != value))
				{
					if (this._TM_Local.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlocal_idChanging(value);
					this.SendPropertyChanging();
					this._local_id = value;
					this.SendPropertyChanged("local_id");
					this.Onlocal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Local_TM_Empleados", Storage="_TM_Local", ThisKey="local_id", OtherKey="local_id", IsForeignKey=true)]
		public TM_Local TM_Local
		{
			get
			{
				return this._TM_Local.Entity;
			}
			set
			{
				TM_Local previousValue = this._TM_Local.Entity;
				if (((previousValue != value) 
							|| (this._TM_Local.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Local.Entity = null;
						previousValue.TM_Empleados.Remove(this);
					}
					this._TM_Local.Entity = value;
					if ((value != null))
					{
						value.TM_Empleados.Add(this);
						this._local_id = value.local_id;
					}
					else
					{
						this._local_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Local");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_HamMaker")]
	public partial class TM_HamMaker : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HamMakerId;
		
		private string _Nombre;
		
		private System.Nullable<int> _cliente_id;
		
		private System.Nullable<int> _IngredientesId;
		
		private EntityRef<TM_Clientes> _TM_Clientes;
		
		private EntityRef<TM_Ingredientes> _TM_Ingredientes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHamMakerIdChanging(int value);
    partial void OnHamMakerIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void Oncliente_idChanging(System.Nullable<int> value);
    partial void Oncliente_idChanged();
    partial void OnIngredientesIdChanging(System.Nullable<int> value);
    partial void OnIngredientesIdChanged();
    #endregion
		
		public TM_HamMaker()
		{
			this._TM_Clientes = default(EntityRef<TM_Clientes>);
			this._TM_Ingredientes = default(EntityRef<TM_Ingredientes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HamMakerId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int HamMakerId
		{
			get
			{
				return this._HamMakerId;
			}
			set
			{
				if ((this._HamMakerId != value))
				{
					this.OnHamMakerIdChanging(value);
					this.SendPropertyChanging();
					this._HamMakerId = value;
					this.SendPropertyChanged("HamMakerId");
					this.OnHamMakerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliente_id", DbType="Int")]
		public System.Nullable<int> cliente_id
		{
			get
			{
				return this._cliente_id;
			}
			set
			{
				if ((this._cliente_id != value))
				{
					if (this._TM_Clientes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncliente_idChanging(value);
					this.SendPropertyChanging();
					this._cliente_id = value;
					this.SendPropertyChanged("cliente_id");
					this.Oncliente_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientesId", DbType="Int")]
		public System.Nullable<int> IngredientesId
		{
			get
			{
				return this._IngredientesId;
			}
			set
			{
				if ((this._IngredientesId != value))
				{
					if (this._TM_Ingredientes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIngredientesIdChanging(value);
					this.SendPropertyChanging();
					this._IngredientesId = value;
					this.SendPropertyChanged("IngredientesId");
					this.OnIngredientesIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Clientes_TM_HamMaker", Storage="_TM_Clientes", ThisKey="cliente_id", OtherKey="cliente_id", IsForeignKey=true)]
		public TM_Clientes TM_Clientes
		{
			get
			{
				return this._TM_Clientes.Entity;
			}
			set
			{
				TM_Clientes previousValue = this._TM_Clientes.Entity;
				if (((previousValue != value) 
							|| (this._TM_Clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Clientes.Entity = null;
						previousValue.TM_HamMaker.Remove(this);
					}
					this._TM_Clientes.Entity = value;
					if ((value != null))
					{
						value.TM_HamMaker.Add(this);
						this._cliente_id = value.cliente_id;
					}
					else
					{
						this._cliente_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Clientes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Ingredientes_TM_HamMaker", Storage="_TM_Ingredientes", ThisKey="IngredientesId", OtherKey="IngredientesId", IsForeignKey=true)]
		public TM_Ingredientes TM_Ingredientes
		{
			get
			{
				return this._TM_Ingredientes.Entity;
			}
			set
			{
				TM_Ingredientes previousValue = this._TM_Ingredientes.Entity;
				if (((previousValue != value) 
							|| (this._TM_Ingredientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Ingredientes.Entity = null;
						previousValue.TM_HamMaker.Remove(this);
					}
					this._TM_Ingredientes.Entity = value;
					if ((value != null))
					{
						value.TM_HamMaker.Add(this);
						this._IngredientesId = value.IngredientesId;
					}
					else
					{
						this._IngredientesId = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Ingredientes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Ingredientes")]
	public partial class TM_Ingredientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IngredientesId;
		
		private string _Pan;
		
		private string _Carnes;
		
		private string _Vegetales;
		
		private string _Cebolla;
		
		private string _Queso;
		
		private string _Salsa;
		
		private System.Nullable<int> _MenuId;
		
		private EntitySet<TM_HamMaker> _TM_HamMaker;
		
		private EntityRef<TM_Menu> _TM_Menu;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIngredientesIdChanging(int value);
    partial void OnIngredientesIdChanged();
    partial void OnPanChanging(string value);
    partial void OnPanChanged();
    partial void OnCarnesChanging(string value);
    partial void OnCarnesChanged();
    partial void OnVegetalesChanging(string value);
    partial void OnVegetalesChanged();
    partial void OnCebollaChanging(string value);
    partial void OnCebollaChanged();
    partial void OnQuesoChanging(string value);
    partial void OnQuesoChanged();
    partial void OnSalsaChanging(string value);
    partial void OnSalsaChanged();
    partial void OnMenuIdChanging(System.Nullable<int> value);
    partial void OnMenuIdChanged();
    #endregion
		
		public TM_Ingredientes()
		{
			this._TM_HamMaker = new EntitySet<TM_HamMaker>(new Action<TM_HamMaker>(this.attach_TM_HamMaker), new Action<TM_HamMaker>(this.detach_TM_HamMaker));
			this._TM_Menu = default(EntityRef<TM_Menu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientesId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IngredientesId
		{
			get
			{
				return this._IngredientesId;
			}
			set
			{
				if ((this._IngredientesId != value))
				{
					this.OnIngredientesIdChanging(value);
					this.SendPropertyChanging();
					this._IngredientesId = value;
					this.SendPropertyChanged("IngredientesId");
					this.OnIngredientesIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pan", DbType="VarChar(100)")]
		public string Pan
		{
			get
			{
				return this._Pan;
			}
			set
			{
				if ((this._Pan != value))
				{
					this.OnPanChanging(value);
					this.SendPropertyChanging();
					this._Pan = value;
					this.SendPropertyChanged("Pan");
					this.OnPanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carnes", DbType="VarChar(100)")]
		public string Carnes
		{
			get
			{
				return this._Carnes;
			}
			set
			{
				if ((this._Carnes != value))
				{
					this.OnCarnesChanging(value);
					this.SendPropertyChanging();
					this._Carnes = value;
					this.SendPropertyChanged("Carnes");
					this.OnCarnesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vegetales", DbType="VarChar(100)")]
		public string Vegetales
		{
			get
			{
				return this._Vegetales;
			}
			set
			{
				if ((this._Vegetales != value))
				{
					this.OnVegetalesChanging(value);
					this.SendPropertyChanging();
					this._Vegetales = value;
					this.SendPropertyChanged("Vegetales");
					this.OnVegetalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cebolla", DbType="VarChar(100)")]
		public string Cebolla
		{
			get
			{
				return this._Cebolla;
			}
			set
			{
				if ((this._Cebolla != value))
				{
					this.OnCebollaChanging(value);
					this.SendPropertyChanging();
					this._Cebolla = value;
					this.SendPropertyChanged("Cebolla");
					this.OnCebollaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Queso", DbType="VarChar(100)")]
		public string Queso
		{
			get
			{
				return this._Queso;
			}
			set
			{
				if ((this._Queso != value))
				{
					this.OnQuesoChanging(value);
					this.SendPropertyChanging();
					this._Queso = value;
					this.SendPropertyChanged("Queso");
					this.OnQuesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salsa", DbType="VarChar(100)")]
		public string Salsa
		{
			get
			{
				return this._Salsa;
			}
			set
			{
				if ((this._Salsa != value))
				{
					this.OnSalsaChanging(value);
					this.SendPropertyChanging();
					this._Salsa = value;
					this.SendPropertyChanged("Salsa");
					this.OnSalsaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuId", DbType="Int")]
		public System.Nullable<int> MenuId
		{
			get
			{
				return this._MenuId;
			}
			set
			{
				if ((this._MenuId != value))
				{
					if (this._TM_Menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMenuIdChanging(value);
					this.SendPropertyChanging();
					this._MenuId = value;
					this.SendPropertyChanged("MenuId");
					this.OnMenuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Ingredientes_TM_HamMaker", Storage="_TM_HamMaker", ThisKey="IngredientesId", OtherKey="IngredientesId")]
		public EntitySet<TM_HamMaker> TM_HamMaker
		{
			get
			{
				return this._TM_HamMaker;
			}
			set
			{
				this._TM_HamMaker.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Menu_TM_Ingredientes", Storage="_TM_Menu", ThisKey="MenuId", OtherKey="MenuId", IsForeignKey=true)]
		public TM_Menu TM_Menu
		{
			get
			{
				return this._TM_Menu.Entity;
			}
			set
			{
				TM_Menu previousValue = this._TM_Menu.Entity;
				if (((previousValue != value) 
							|| (this._TM_Menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Menu.Entity = null;
						previousValue.TM_Ingredientes.Remove(this);
					}
					this._TM_Menu.Entity = value;
					if ((value != null))
					{
						value.TM_Ingredientes.Add(this);
						this._MenuId = value.MenuId;
					}
					else
					{
						this._MenuId = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Menu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TM_HamMaker(TM_HamMaker entity)
		{
			this.SendPropertyChanging();
			entity.TM_Ingredientes = this;
		}
		
		private void detach_TM_HamMaker(TM_HamMaker entity)
		{
			this.SendPropertyChanging();
			entity.TM_Ingredientes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Local")]
	public partial class TM_Local : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _local_id;
		
		private string _nombre;
		
		private string _direccion;
		
		private EntitySet<TM_Clientes> _TM_Clientes;
		
		private EntitySet<TM_Contabilidad> _TM_Contabilidad;
		
		private EntitySet<TM_Empleados> _TM_Empleados;
		
		private EntitySet<TM_Menu> _TM_Menu;
		
		private EntitySet<TM_Pedidos> _TM_Pedidos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlocal_idChanging(int value);
    partial void Onlocal_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    #endregion
		
		public TM_Local()
		{
			this._TM_Clientes = new EntitySet<TM_Clientes>(new Action<TM_Clientes>(this.attach_TM_Clientes), new Action<TM_Clientes>(this.detach_TM_Clientes));
			this._TM_Contabilidad = new EntitySet<TM_Contabilidad>(new Action<TM_Contabilidad>(this.attach_TM_Contabilidad), new Action<TM_Contabilidad>(this.detach_TM_Contabilidad));
			this._TM_Empleados = new EntitySet<TM_Empleados>(new Action<TM_Empleados>(this.attach_TM_Empleados), new Action<TM_Empleados>(this.detach_TM_Empleados));
			this._TM_Menu = new EntitySet<TM_Menu>(new Action<TM_Menu>(this.attach_TM_Menu), new Action<TM_Menu>(this.detach_TM_Menu));
			this._TM_Pedidos = new EntitySet<TM_Pedidos>(new Action<TM_Pedidos>(this.attach_TM_Pedidos), new Action<TM_Pedidos>(this.detach_TM_Pedidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_local_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int local_id
		{
			get
			{
				return this._local_id;
			}
			set
			{
				if ((this._local_id != value))
				{
					this.Onlocal_idChanging(value);
					this.SendPropertyChanging();
					this._local_id = value;
					this.SendPropertyChanged("local_id");
					this.Onlocal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Local_TM_Clientes", Storage="_TM_Clientes", ThisKey="local_id", OtherKey="local_id")]
		public EntitySet<TM_Clientes> TM_Clientes
		{
			get
			{
				return this._TM_Clientes;
			}
			set
			{
				this._TM_Clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Local_TM_Contabilidad", Storage="_TM_Contabilidad", ThisKey="local_id", OtherKey="local_id")]
		public EntitySet<TM_Contabilidad> TM_Contabilidad
		{
			get
			{
				return this._TM_Contabilidad;
			}
			set
			{
				this._TM_Contabilidad.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Local_TM_Empleados", Storage="_TM_Empleados", ThisKey="local_id", OtherKey="local_id")]
		public EntitySet<TM_Empleados> TM_Empleados
		{
			get
			{
				return this._TM_Empleados;
			}
			set
			{
				this._TM_Empleados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Local_TM_Menu", Storage="_TM_Menu", ThisKey="local_id", OtherKey="local_id")]
		public EntitySet<TM_Menu> TM_Menu
		{
			get
			{
				return this._TM_Menu;
			}
			set
			{
				this._TM_Menu.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Local_TM_Pedidos", Storage="_TM_Pedidos", ThisKey="local_id", OtherKey="local_id")]
		public EntitySet<TM_Pedidos> TM_Pedidos
		{
			get
			{
				return this._TM_Pedidos;
			}
			set
			{
				this._TM_Pedidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TM_Clientes(TM_Clientes entity)
		{
			this.SendPropertyChanging();
			entity.TM_Local = this;
		}
		
		private void detach_TM_Clientes(TM_Clientes entity)
		{
			this.SendPropertyChanging();
			entity.TM_Local = null;
		}
		
		private void attach_TM_Contabilidad(TM_Contabilidad entity)
		{
			this.SendPropertyChanging();
			entity.TM_Local = this;
		}
		
		private void detach_TM_Contabilidad(TM_Contabilidad entity)
		{
			this.SendPropertyChanging();
			entity.TM_Local = null;
		}
		
		private void attach_TM_Empleados(TM_Empleados entity)
		{
			this.SendPropertyChanging();
			entity.TM_Local = this;
		}
		
		private void detach_TM_Empleados(TM_Empleados entity)
		{
			this.SendPropertyChanging();
			entity.TM_Local = null;
		}
		
		private void attach_TM_Menu(TM_Menu entity)
		{
			this.SendPropertyChanging();
			entity.TM_Local = this;
		}
		
		private void detach_TM_Menu(TM_Menu entity)
		{
			this.SendPropertyChanging();
			entity.TM_Local = null;
		}
		
		private void attach_TM_Pedidos(TM_Pedidos entity)
		{
			this.SendPropertyChanging();
			entity.TM_Local = this;
		}
		
		private void detach_TM_Pedidos(TM_Pedidos entity)
		{
			this.SendPropertyChanging();
			entity.TM_Local = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Menu")]
	public partial class TM_Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MenuId;
		
		private string _Hamburguesas;
		
		private string _Bebidas;
		
		private string _Postres;
		
		private string _Extras;
		
		private System.Nullable<int> _local_id;
		
		private EntitySet<TM_Ingredientes> _TM_Ingredientes;
		
		private EntityRef<TM_Local> _TM_Local;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuIdChanging(int value);
    partial void OnMenuIdChanged();
    partial void OnHamburguesasChanging(string value);
    partial void OnHamburguesasChanged();
    partial void OnBebidasChanging(string value);
    partial void OnBebidasChanged();
    partial void OnPostresChanging(string value);
    partial void OnPostresChanged();
    partial void OnExtrasChanging(string value);
    partial void OnExtrasChanged();
    partial void Onlocal_idChanging(System.Nullable<int> value);
    partial void Onlocal_idChanged();
    #endregion
		
		public TM_Menu()
		{
			this._TM_Ingredientes = new EntitySet<TM_Ingredientes>(new Action<TM_Ingredientes>(this.attach_TM_Ingredientes), new Action<TM_Ingredientes>(this.detach_TM_Ingredientes));
			this._TM_Local = default(EntityRef<TM_Local>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MenuId
		{
			get
			{
				return this._MenuId;
			}
			set
			{
				if ((this._MenuId != value))
				{
					this.OnMenuIdChanging(value);
					this.SendPropertyChanging();
					this._MenuId = value;
					this.SendPropertyChanged("MenuId");
					this.OnMenuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hamburguesas", DbType="VarChar(100)")]
		public string Hamburguesas
		{
			get
			{
				return this._Hamburguesas;
			}
			set
			{
				if ((this._Hamburguesas != value))
				{
					this.OnHamburguesasChanging(value);
					this.SendPropertyChanging();
					this._Hamburguesas = value;
					this.SendPropertyChanged("Hamburguesas");
					this.OnHamburguesasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bebidas", DbType="VarChar(100)")]
		public string Bebidas
		{
			get
			{
				return this._Bebidas;
			}
			set
			{
				if ((this._Bebidas != value))
				{
					this.OnBebidasChanging(value);
					this.SendPropertyChanging();
					this._Bebidas = value;
					this.SendPropertyChanged("Bebidas");
					this.OnBebidasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postres", DbType="VarChar(100)")]
		public string Postres
		{
			get
			{
				return this._Postres;
			}
			set
			{
				if ((this._Postres != value))
				{
					this.OnPostresChanging(value);
					this.SendPropertyChanging();
					this._Postres = value;
					this.SendPropertyChanged("Postres");
					this.OnPostresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extras", DbType="VarChar(100)")]
		public string Extras
		{
			get
			{
				return this._Extras;
			}
			set
			{
				if ((this._Extras != value))
				{
					this.OnExtrasChanging(value);
					this.SendPropertyChanging();
					this._Extras = value;
					this.SendPropertyChanged("Extras");
					this.OnExtrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_local_id", DbType="Int")]
		public System.Nullable<int> local_id
		{
			get
			{
				return this._local_id;
			}
			set
			{
				if ((this._local_id != value))
				{
					if (this._TM_Local.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlocal_idChanging(value);
					this.SendPropertyChanging();
					this._local_id = value;
					this.SendPropertyChanged("local_id");
					this.Onlocal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Menu_TM_Ingredientes", Storage="_TM_Ingredientes", ThisKey="MenuId", OtherKey="MenuId")]
		public EntitySet<TM_Ingredientes> TM_Ingredientes
		{
			get
			{
				return this._TM_Ingredientes;
			}
			set
			{
				this._TM_Ingredientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Local_TM_Menu", Storage="_TM_Local", ThisKey="local_id", OtherKey="local_id", IsForeignKey=true)]
		public TM_Local TM_Local
		{
			get
			{
				return this._TM_Local.Entity;
			}
			set
			{
				TM_Local previousValue = this._TM_Local.Entity;
				if (((previousValue != value) 
							|| (this._TM_Local.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Local.Entity = null;
						previousValue.TM_Menu.Remove(this);
					}
					this._TM_Local.Entity = value;
					if ((value != null))
					{
						value.TM_Menu.Add(this);
						this._local_id = value.local_id;
					}
					else
					{
						this._local_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Local");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TM_Ingredientes(TM_Ingredientes entity)
		{
			this.SendPropertyChanging();
			entity.TM_Menu = this;
		}
		
		private void detach_TM_Ingredientes(TM_Ingredientes entity)
		{
			this.SendPropertyChanging();
			entity.TM_Menu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Pedidos")]
	public partial class TM_Pedidos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PedidosId;
		
		private string _Pedido;
		
		private string _Descripcion;
		
		private System.Nullable<int> _registro_id;
		
		private System.Nullable<int> _local_id;
		
		private EntitySet<TM_Clientes> _TM_Clientes;
		
		private EntityRef<TM_Local> _TM_Local;
		
		private EntityRef<TM_Contabilidad> _TM_Contabilidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPedidosIdChanging(int value);
    partial void OnPedidosIdChanged();
    partial void OnPedidoChanging(string value);
    partial void OnPedidoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void Onregistro_idChanging(System.Nullable<int> value);
    partial void Onregistro_idChanged();
    partial void Onlocal_idChanging(System.Nullable<int> value);
    partial void Onlocal_idChanged();
    #endregion
		
		public TM_Pedidos()
		{
			this._TM_Clientes = new EntitySet<TM_Clientes>(new Action<TM_Clientes>(this.attach_TM_Clientes), new Action<TM_Clientes>(this.detach_TM_Clientes));
			this._TM_Local = default(EntityRef<TM_Local>);
			this._TM_Contabilidad = default(EntityRef<TM_Contabilidad>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PedidosId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PedidosId
		{
			get
			{
				return this._PedidosId;
			}
			set
			{
				if ((this._PedidosId != value))
				{
					this.OnPedidosIdChanging(value);
					this.SendPropertyChanging();
					this._PedidosId = value;
					this.SendPropertyChanged("PedidosId");
					this.OnPedidosIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pedido", DbType="VarChar(100)")]
		public string Pedido
		{
			get
			{
				return this._Pedido;
			}
			set
			{
				if ((this._Pedido != value))
				{
					this.OnPedidoChanging(value);
					this.SendPropertyChanging();
					this._Pedido = value;
					this.SendPropertyChanged("Pedido");
					this.OnPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registro_id", DbType="Int")]
		public System.Nullable<int> registro_id
		{
			get
			{
				return this._registro_id;
			}
			set
			{
				if ((this._registro_id != value))
				{
					if (this._TM_Contabilidad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onregistro_idChanging(value);
					this.SendPropertyChanging();
					this._registro_id = value;
					this.SendPropertyChanged("registro_id");
					this.Onregistro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_local_id", DbType="Int")]
		public System.Nullable<int> local_id
		{
			get
			{
				return this._local_id;
			}
			set
			{
				if ((this._local_id != value))
				{
					if (this._TM_Local.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlocal_idChanging(value);
					this.SendPropertyChanging();
					this._local_id = value;
					this.SendPropertyChanged("local_id");
					this.Onlocal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Pedidos_TM_Clientes", Storage="_TM_Clientes", ThisKey="PedidosId", OtherKey="PedidosID")]
		public EntitySet<TM_Clientes> TM_Clientes
		{
			get
			{
				return this._TM_Clientes;
			}
			set
			{
				this._TM_Clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Local_TM_Pedidos", Storage="_TM_Local", ThisKey="local_id", OtherKey="local_id", IsForeignKey=true)]
		public TM_Local TM_Local
		{
			get
			{
				return this._TM_Local.Entity;
			}
			set
			{
				TM_Local previousValue = this._TM_Local.Entity;
				if (((previousValue != value) 
							|| (this._TM_Local.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Local.Entity = null;
						previousValue.TM_Pedidos.Remove(this);
					}
					this._TM_Local.Entity = value;
					if ((value != null))
					{
						value.TM_Pedidos.Add(this);
						this._local_id = value.local_id;
					}
					else
					{
						this._local_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Local");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Contabilidad_TM_Pedidos", Storage="_TM_Contabilidad", ThisKey="registro_id", OtherKey="registro_id", IsForeignKey=true)]
		public TM_Contabilidad TM_Contabilidad
		{
			get
			{
				return this._TM_Contabilidad.Entity;
			}
			set
			{
				TM_Contabilidad previousValue = this._TM_Contabilidad.Entity;
				if (((previousValue != value) 
							|| (this._TM_Contabilidad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Contabilidad.Entity = null;
						previousValue.TM_Pedidos.Remove(this);
					}
					this._TM_Contabilidad.Entity = value;
					if ((value != null))
					{
						value.TM_Pedidos.Add(this);
						this._registro_id = value.registro_id;
					}
					else
					{
						this._registro_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("TM_Contabilidad");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TM_Clientes(TM_Clientes entity)
		{
			this.SendPropertyChanging();
			entity.TM_Pedidos = this;
		}
		
		private void detach_TM_Clientes(TM_Clientes entity)
		{
			this.SendPropertyChanging();
			entity.TM_Pedidos = null;
		}
	}
}
#pragma warning restore 1591
